### ISSUE TITLE
多个QQ账号群聊列表不加载

### ISSUE THREAD

**Issue by Universebenzene** [axon-oicq/purple-oicq#1]
purple-oicq与libaxon都是1.0.2。新装好后添加第一个账号没问题，第二个账号就会出现只加载好友列表，不加载群聊列表的情况。我曾经试着把 `~/.cache/libaxon` 和 `~/.purple` 全都清空，再删除所有账号然后重新添加，结果现在俩账号都不加载群聊列表了……

别人在群里发消息倒是还能收到，就是没办法自己从列表点进群了。也不清楚是libaxon还是purple-oicq的问题，先在这开issue好了……pidgin我确实也几乎没怎么用过不清楚是不是我自己不会设置……总之还是感谢各位开发者的努力

**Comment by axon-oicq** [comment]
问题应该是因为群列表冲突，群聊列表在 login.c 里被写死了。我看看怎么样弄好一点吧 🤔

https://github.com/axon-oicq/purple-oicq/blob/8ad903272898a7be93d0cecc1da83b7946e5730b/login.c#L77

**Comment by axon-oicq** [comment]
> 第二个账号就会出现只加载好友列表，不加载群聊列表的情况

因为 Pidgin 的问题，我还没找到办法判断群聊列表里是否有制定群聊。现在的处理逻辑是，群聊列表在被新建了以后就不会再同步。我看看怎么解决好一点。

> 我曾经试着把 ~/.cache/libaxon 和 ~/.purple 全都清空，再删除所有账号然后重新添加，结果现在俩账号都不加载群聊列表了……

这个我也不太清除，得靠日志确认 （

**Comment by axon-oicq** [comment]
临时的处理办法是：登录一个帐号，重命名自动同步的群聊列表（比如叫 群聊列表 A），登录另一个帐号，应该会再得到一份群聊列表。

**Comment by axon-oicq** [comment]
应该在 6d6a338 修复了

**Comment by Universebenzene** [comment]
试了AUR上的purple-oicq-git，好像确实两个号都能加载群列表了，感谢修复
